[tool.poetry]
name = "core"
version = "0.1.0"
description = "core is a simple tool to help you manage your media files."
authors = ["core <core@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"