[tool.poetry]
name = "ProjectblingCore"
version = "0.3.0"
description = "core lib for Projectbling"
authors = ["core <core@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"